#!/usr/bin/env bash
# DNS Plugin Configuration

export PLUGIN_COMMAND_PREFIX="dns"
export PLUGIN_SERVICE="DNS"
export PLUGIN_DATA_ROOT=${PLUGIN_DATA_ROOT:-${DNS_ROOT:="${DOKKU_LIB_ROOT:-/var/lib/dokku}/services/dns"}}
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:-${DNS_CONFIG_ROOT:="${DOKKU_LIB_ROOT:-/var/lib/dokku}/config/dns"}}

PLUGIN_BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PLUGIN_BASE_PATH
export DOKKU_BIN="${DOKKU_BIN:-/usr/bin/dokku}"

# Used by bin/generate for README generation
export PLUGIN_VARIABLE="DNS"
export PLUGIN_DEFAULT_ALIAS="DNS"
export PLUGIN_SCHEME="dns"
export PLUGIN_DATASTORE_PORTS=("53")
