#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

# Load dokku functions
if [[ -f "$PLUGIN_CORE_AVAILABLE_PATH/common/functions" ]]; then
  source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
fi

# Load common fallback functions
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/common-functions"

dns-triggers-cmd() {
  declare desc="show DNS automatic management status"
  
  local TRIGGERS_ENABLED_FILE="$PLUGIN_DATA_ROOT/TRIGGERS_ENABLED"
  
  if [[ -f "$TRIGGERS_ENABLED_FILE" ]]; then
    dokku_log_info1 "DNS automatic management: enabled"
  else
    dokku_log_info1 "DNS automatic management: disabled"
  fi
}

dns-triggers-cmd "$@"