#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

dns-triggers-cmd() {
  declare desc="show DNS automatic management status"

  if dns_property_exists "--global" "TRIGGERS_ENABLED"; then
    dokku_log_info1 "DNS automatic management: enabled"
  else
    dokku_log_info1 "DNS automatic management: disabled"
  fi
}

dns-triggers-cmd "$@"
